# Generated by Django 4.1.7 on 2023-03-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('telegram', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('applied', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('favorite_map', models.CharField(max_length=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.game')),
            ],
        ),
    ]
